-- 8000 is "too many values to unpack"
-- who says this, huh? propaganda from Big Upvalue?
local limit = 8000 - 1

-- top=8198 in -O0
-- point i'm trying to make is that you have to do some insane stuff to get top this high, so we probably can store it as a smaller integer

-- 198 VARIABLES
-- any more and compiling crashes
-- (max 255 registers, max 200 local registers, -O1 and -O2 optimise them away)
local a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a
local x = {
	table.unpack(table.create(limit, 0)),
}
print(a)
