--!strict
-- service declarations
-- players, used everywhere

local Players = game:GetService "Players"
local RunService = game:GetService "RunService" -- heartbeat
local Workspace = game:GetService "Workspace"

local NotAService = 5
const TweenService = game:GetService "TweenService"
const ReplicatedStorage = game:GetService "ReplicatedStorage"
const ServerStorage = game:GetService "ServerStorage"
