--!strict
-- service declarations

local Workspace = game:GetService "Workspace"
-- players, used everywhere
local Players = game:GetService("Players")
local RunService = game:GetService "RunService" -- heartbeat

local NotAService = 5

const TweenService = game:GetService "TweenService"
const ReplicatedStorage = game:GetService "ReplicatedStorage"
const ServerStorage = game:GetService "ServerStorage"
