while 1 do -- comment 2 lel
	-- comment 3 lel
	print(function() return 5 end)
	while 2 do -- comment 2 lel
		-- comment 3 lel
		print(function() return 5 end)
		while 3 do -- comment 2 lel
			-- comment 3 lel
			print(function() return 5 end)
			while 4 do -- comment 2 lel
				-- comment 3 lel
				print(function() return 5 end)
			end -- comment lel
		end -- comment lel
	end -- comment lel
end -- comment lel
